version: '3.8'

services:
  logsense:
    build: .
    container_name: logsense-app
    ports:
      - "8081:8081"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: >
      sh -c "
      /bin/ollama serve &
      sleep 5 &&
      ollama pull gemma:2b &&
      ollama cp gemma:2b gemma &&
      tail -f /dev/null
      "

volumes:
  ollama_data:
